spring:
  application:
    name: identity-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:192.168.17.132:8848}
        namespace: ${NACOS_NAMESPACE:} # Default to empty (public)
      config:
        server-addr: ${NACOS_SERVER:192.168.17.132:8848}
        file-extension: yml
        namespace: ${NACOS_NAMESPACE:}
  config:
    import: optional:nacos:identity-service.yml