spring.application.name=engagement-service
server.port=8082

# Database Configuration - create 'uniway_engagement' in pgAdmin later
spring.datasource.url=jdbc:postgresql://localhost:5432/uniway_engagement
spring.datasource.username=postgres
spring.datasource.password=Shailu@.12

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Secret - Must match your colleague's Identity Service secret
jwt.secret=VGhpc0lzQVN0cm9uZ0Jhc2U2NFNlY3JldEtleUZvckpXVEF1dGhFbmNvZGluZw==